;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-or-skip-quote
        keyboard-escape-quit
        kill-rectangle
        kill-region
        move-text-up
        sh-assignment
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        autopair-insert-opening
        autopair-newline
        delete-window
        electric-newline-and-maybe-indent
        ido-kill-buffer
        ido-switch-buffer
        mc/toggle-cursor-at-point
        multiple-cursors-mode
        repeat
        save-buffers-kill-terminal
        suspend-frame
        tab-to-tab-stop
        undo-tree-visualize
        upcase-region
        xterm-paste
        yank-rectangle
        ))
