;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-or-skip-quote
	keyboard-escape-quit
	kill-rectangle
	kill-region
	))

(setq mc/cmds-to-run-once
      '(
	autopair-newline
	electric-newline-and-maybe-indent
	ido-switch-buffer
	repeat
	suspend-frame
	tab-to-tab-stop
	undo-tree-visualize
	upcase-region
	))
